#!/bin/bash

# Run salientos hooks related commands.

Lsb_release() {
    local file=/etc/lsb-release

    if [[ -z "`grep "^DISTRIB_RELEASE=" $file`" ]] ; then
        # add missing DISTRIB_RELEASE=
        echo "DISTRIB_RELEASE=rolling" >> "$file"
    fi
    sed -i "$file" \
        -e 's|^DISTRIB_ID=.*$|DISTRIB_ID=salientos|' \
        -e 's|^DISTRIB_RELEASE=.*$|DISTRIB_RELEASE=rolling|' \
        -e 's|^DISTRIB_DESCRIPTION=.*$|DISTRIB_DESCRIPTION=\"SalientOS\"|'
}

Os_release() {
    local file=/usr/lib/os-release
	
    sed -i $file \
        -e 's|^NAME=.*$|NAME=\"SalientOS\"|' \
        -e 's|^PRETTY_NAME=.*$|PRETTY_NAME=\"SalientOS\"|' \
        -e 's|^ID=.*$|ID=salientos|' \
    	-e 's|^ID_LIKE=.*$|ID_LIKE=arch|' \
    	-e 's|^BUILD_ID=.*$|BUILD_ID=rolling|' \
		-e 's|^ANSI_COLOR=.*$|ANSI_COLOR=\"0;36;23;147;209\"|' \
        -e 's|^HOME_URL=.*$|HOME_URL=\"https://salientos.org\"|' \
		-e 's|^DOCUMENTATION_URL=.*$|DOCUMENTATION_URL=\"https://salientos.org\"|' \
        -e 's|^SUPPORT_URL=.*$|SUPPORT_URL=\"https://sourceforge.net/p/salient-os/discussion\"|' \
        -e 's|^BUG_REPORT_URL=.*$|BUG_REPORT_URL=\"https://sourceforge.net/p/salient-os/tickets\"|' \
        -e 's|^LOGO=.*$|LOGO=salientos|' \

	if [ -z "$(grep "^ID_LIKE=" $file)" ] && [ -n "$(grep "^ID=" $file)" ] ; then
        # add missing ID_LIKE=
        sed -i $file -e '/^ID=/a \ID_LIKE=arch'
    fi
}

Issues() {
    sed -i 's|Arch Linux|SalientOS|g' /etc/issue /usr/share/factory/etc/issue
}

Main()
{
    local hookname="$1"

    case "$hookname" in
        os-release)  Os_release ;;
        lsb-release) Lsb_release ;;
        "")          Os_release
                     Lsb_release
                     Issues
                     ;;
    esac
}

Main "$@"

