#!/bin/bash

# Run salientos hooks related commands.

Lsb_release() {
    local file=/etc/lsb-release

    if [ -z "$(grep "^DISTRIB_CODENAME=" $file)" ] ; then
        # add missing DISTRIB_CODENAME=
        echo "DISTRIB_CODENAME=rolling" >> $file
    fi
    sed -i $file \
        -e 's|^DISTRIB_ID=.*$|DISTRIB_ID=salientos|' \
        -e 's|^DISTRIB_CODENAME=.*$|DISTRIB_CODENAME=rolling|' \
        -e 's|^DISTRIB_DESCRIPTION=.*$|DISTRIB_DESCRIPTION=\"Salient OS\"|'
}

Os_release() {
    local file=/usr/lib/os-release
    local salientosfile=/usr/lib/salientos-release

    sed -i $file \
        -e 's|^NAME=.*$|NAME=\"Salient OS\"|' \
        -e 's|^PRETTY_NAME=.*$|PRETTY_NAME=\"Salient OS\"|' \
        -e 's|^HOME_URL=.*$|HOME_URL=\"https://salientos.github.io\"|' \
        -e 's|^SUPPORT_URL=.*$|SUPPORT_URL=\"https://sourceforge.net/p/salient-os/discussion\"|' \
        -e 's|^BUG_REPORT_URL=.*$|BUG_REPORT_URL=\"https://sourceforge.net/p/salient-os/tickets\"|' \
        -e 's|^LOGO=.*$|LOGO=/usr/share/pixmaps/salientos/logo.png|' \
        -e 's|^ID=.*$|ID=salientos|' \
        -e 's|^ID_LIKE=.*$|ID_LIKE=arch|'

    if [ -z "$(grep "^ID_LIKE=" $file)" ] && [ -n "$(grep "^ID=" $file)" ] ; then
        # add missing ID_LIKE=
        sed -i $file -e '/^ID=/a \ID_LIKE=arch'
    fi
    if [ -r $salientosfile ] ; then
        # fix BUILD_ID for Salient OS
        local buildid="$(grep "^VERSION=" $salientosfile | awk '{print $1}' | cut -d '=' -f 2)"
        sed -i $file -e "s|^BUILD_ID=.*$|BUILD_ID=$buildid|"
    fi
}

Issues() {
    sed -i 's|Arch|Salient OS|g' /etc/issue /usr/share/factory/etc/issue
}

Main()
{
    local hookname="$1"

    case "$hookname" in
        os-release)  Os_release ;;
        lsb-release) Lsb_release ;;
        "")          Os_release
                     Lsb_release
                     Issues
                     ;;
    esac
}

Main "$@"
